name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your main branch name if different

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.14'

    - name: Install dependencies
      run: npm install # Or yarn install if you're using yarn

    - name: Build website
      run: npm run build # Or whatever command is required to build your website

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./build # Update this to the directory containing your built website
        publish_branch: gh-pages

    - name: Configure Nginx
      run: |
        echo 'worker_processes  1;

        events {
            worker_connections  1024;
        }

        http {
            include       mime.types;
            default_type  application/octet-stream;

            sendfile        on;
            keepalive_timeout  65;

            server {
                listen       2022;
                server_name  192.168.29.84;

                location / {
                    root   C:/Users/ADMIN/Desktop/selftest/actions-runner/grcdeploy/GRC_angulardeploy/GRC_angulardeploy/dist/grc/browser;
                    index  index.html index.htm;
                }

                error_page   500 502 503 504  /50x.html;
                location = /50x.html {
                    root   html;
                }
            }
        }' > C:/Users/ADMIN/Desktop/nginx-1.25.4/conf/nginx.conf # Update the path to your nginx.conf file

    - name: Start Nginx
      run: |
        cd C:/Users/ADMIN/Desktop/nginx-1.25.4/conf/
        ./nginx
