jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: powershell -File ./scripts/build_and_deploy.ps1

      - name: Setup and Start Nginx
        run: powershell -File ./scripts/setup_nginx.ps1
