name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your main branch name if different

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Working Directory
        run: pwd
        shell: powershell

      - name: Set Execution Policy
        run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        shell: powershell
        
      - name: List files in scripts directory
        run: dir "./scripts"
        shell: powershell

      - name: Build and Deploy
        run: powershell -File "./scripts/build_and_deploy.ps1"

      - name: Setup and Start Nginx
        run: powershell -File "./scripts/setup_nginx.ps1"
